apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service
  namespace: car-rental-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-service
  template:
    metadata:
      labels:
        app: car-service
    spec:
      affinity: # Punkt 2c: Rozmieszczenie obiektów (anty-powinowactwo podów - nie chcemy ich na tym samym węźle, jeśli byłoby ich więcej)
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - car-service
      containers:
        - name: car-service-app
          image: car_service_app:latest # Zakładamy lokalny obraz w Minikube
          imagePullPolicy: Never # Ważne dla Minikube, czyta obraz z lokalnego dockera
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: rental-config
                  key: MONGO_URL
          resources: # Punkt 2a: Ograniczenie zasobów
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: "100m"
              memory: 128Mi
          healthCheck: # Odpowiednik healthcheck z docker-compose
            livenessProbe:
              httpGet:
                path: /
                port: 8000
              initialDelaySeconds: 15
              periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: car-service-service
  namespace: car-rental-ns
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: car-service