apiVersion: v1
kind: ConfigMap
metadata:
  name: rental-config
  namespace: car-rental-ns
data:
  MONGO_URL: "mongodb://mongodb-service:27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: rental-secret
  namespace: car-rental-ns
type: Opaque
data:
  APP_SECRET_KEY: c3VwZXItc2VjcmV0LWtleQ==