apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: car-rental-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: kubaaa0105/car-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: 256Mi
            requests:
              cpu: "100m"
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: car-rental-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend