apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: car-rental-ns
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: car-service
        - podSelector:
            matchLabels:
              app: rental-service
      ports:
        - protocol: TCP
          port: 27017