apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: car-rental-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # Domyślna klasa w Minikube automatycznie utworzy PV
  resources:
    requests:
      storage: 2Gi