apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-service
  namespace: car-rental-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rental-service
  template:
    metadata:
      labels:
        app: rental-service
    spec:
      containers:
        - name: rental-service-app
          image: vexim/rental-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: rental-config
                  key: MONGO_URL
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: "100m"
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rental-service-service
  namespace: car-rental-ns
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: rental-service